import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The Studio is a standalone app with its own deps and lint config.
    "studio/**",
    // Vendored skill references, not project source.
    "agent/**",
    ".agents/**",
    // Generated by `npm run typegen` in studio/. Not hand-edited, so linting it
    // only produces noise about shapes TypeGen chose.
    "sanity.types.ts",
  ]),
]);

export default eslintConfig;
